name: Update Ghost CMS with specific updated markdown file

on:
  push:
    branches:
      - main

jobs:
  update-ghost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get list of changed markdown files
        run: |
          echo "${{ github.event.head_commit.modified }}" | tr -d '[],"' | tr ' ' '\n' | while read file; do
            echo "$file" | grep '\.md$' || continue
            echo "$file" >> changed_files.txt
          done
          if [[ ! -s changed_files.txt ]]; then
            echo "No markdown files changed" >> changed_files.txt
          fi

      - name: Update Ghost CMS
        run: |
          while read file; do
            if [[ -f "$file" ]]; then
              node scripts/sync-ghost.js "$file"
            else
              echo "File $file not found."
            fi
          done < changed_files.txt
